Create a process file application
antho1404/pegasys-hackathon pull request #1
Opened 2019-12-27 03:41 UTC by blackinno

2019-12-29 14:26 UTC, antho1404 requested changes

2019-12-29 14:26 UTC, antho1404 commented on readme.md
> +Make sure that [MESG Core](https://github.com/mesg-foundation/core) is installed and running on your computer.
```suggestion
Make sure that [MESG Engine](https://github.com/mesg-foundation/engine) is installed and running on your computer.
```

2019-12-29 14:26 UTC, antho1404 commented on readme.md
> +## Install MESG Core
```suggestion
## Install MESG Engine
```

2019-12-29 14:26 UTC, antho1404 commented on .env.example
> +CONTRACT_ABI=`cat __PATH_OF_ABI_FILE`
```suggestion
CONTRACT_ABI=`cat abi.json`
```

2019-12-29 14:26 UTC, antho1404 commented on readme.md
> +    --env CONTRACT_ADDRESS=$CONTRACT_ADDRESS \
This command doesn't work

2019-12-30 04:46 UTC, antho1404 commented on application.yml
> +  - tasks: tasks
```suggestion
  - type: task
```

2019-12-30 04:46 UTC, antho1404 commented on application.yml
> +          privateKey: $(env:PRIVATE_KEY)
```suggestion
          privateKey: "$(env:PRIVATE_KEY)"
```

2020-01-02 05:00 UTC, blackinno commented on readme.md
> +    --env CONTRACT_ADDRESS=$CONTRACT_ADDRESS \
Fixed.

2020-01-07 06:07 UTC, antho1404 commented on .env.example
> +CONTRACT_ADDRESS=0x..
```suggestion
CONTRACT_ADDRESS=0x82d8496d668D2E1e298C7B061aA88498Fd068971
```

2020-01-07 06:08 UTC, antho1404 commented on .env.example
> +CONTRACT_ADDRESS=0x..
This is already hardcoded in the UI so we could have it on the env directly

2020-01-07 06:09 UTC, antho1404 approved these changes

2020-01-07 07:08 UTC, merged